"use strict";
// THIS FILE IS AUTOMATICALLY GENERATED. TO UPDATE THIS FILE YOU NEED TO CHANGE THE
// CORRESPONDING JSON SCHEMA FILE, THEN RUN devkit-admin build (or bazel build ...).
Object.defineProperty(exports, "__esModule", { value: true });
exports.SettingOrProject = exports.ProjectSetting = exports.HelpEnum = void 0;
var HelpEnum;
(function (HelpEnum) {
    HelpEnum["HelpJson"] = "JSON";
    HelpEnum["Json"] = "json";
})(HelpEnum = exports.HelpEnum || (exports.HelpEnum = {}));
/**
 * Sets the default analytics enablement status for the project.
 *
 * 为本项目设置使用情况分析的默认启用状态。
 */
var ProjectSetting;
(function (ProjectSetting) {
    ProjectSetting["Off"] = "off";
    ProjectSetting["On"] = "on";
    ProjectSetting["Prompt"] = "prompt";
})(ProjectSetting = exports.ProjectSetting || (exports.ProjectSetting = {}));
/**
 * Directly enables or disables all usage analytics for the user, or prompts the user to set
 * the status interactively, or sets the default status for the project.
 *
 * 直接启用或禁用当前用户的所有使用情况分析，或交互式的提示用户进行设置，或设置项目的默认状态。
 */
var SettingOrProject;
(function (SettingOrProject) {
    SettingOrProject["Ci"] = "ci";
    SettingOrProject["Off"] = "off";
    SettingOrProject["On"] = "on";
    SettingOrProject["Project"] = "project";
    SettingOrProject["Prompt"] = "prompt";
})(SettingOrProject = exports.SettingOrProject || (exports.SettingOrProject = {}));
